/* WHO IS BEING AN ASSHOLE? — frontend
 * Reads data.json (generated by the GitHub Actions cron job) and renders
 * the shame table. All filtering happens client-side so the threshold
 * input works instantly.
 */
(() => {
  "use strict";

  const $ = (id) => document.getElementById(id);

  // Ladder, highest first. CHEEKY's floor is the live threshold input.
  const VERDICTS = [
    { min: 2.00, label: "█ GALACTIC ASSHOLE", cls: "v5", tier: 5 },
    { min: 1.00, label: "█ ASSHOLE", cls: "v4", tier: 4 },
    { min: 0.75, label: "▓ DICK", cls: "v3", tier: 3 },
    { min: 0.50, label: "▓ JERK", cls: "v2", tier: 2 },
    { min: null, label: "▒ CHEEKY", cls: "v1", tier: 1 },
  ];
  const SAINT = { label: "█ SAINT", cls: "v6", tier: 6 };
  const SUPPORTER = { label: "▒ SUPPORTER", cls: "v7", tier: 7 };
  const LOCAL = { label: "░ LOCAL", cls: "v8", tier: 8 };
  const HONEST = { label: "░ HONEST", cls: "v0", tier: 0 };
  const SUS = { label: "▒ SUS", cls: "v9", tier: 9 };

  let data = null;

  // EVE inventory category ids: 6 Ship, 7 Module, 8 Charge (ammo), 18 Drone,
  // 32 Subsystem, 87 Fighter.
  const CATS = {
    ammo: new Set([8, 18]), // charges, drones — fighters live under CAPITALS
    ships: new Set([6]),
    modules: new Set([7, 32]), // modules, rigs, subsystems
    fit: new Set([6, 7, 8, 18, 32, 87]), // union: "everything else" is the complement
  };
  const filters = { min: true, minDir: "<", minMode: "unit", qty: false, qtyDir: "<", cat: "all" };
  let orderMode = "all"; // all | cheapest | priciest — how many rows per item survive
  const vFilter = new Set(); // empty = show every verdict
  let touched = false; // table stays empty until the visitor picks a filter
  const flipped = new Set(); // type_ids whose AVG reference is flipped to Jita

  // Effective reference for a row: AVG-referenced rows can be flipped to
  // their Jita price by clicking the tag.
  function effOf(o) {
    if (o.gal && o.alt != null && flipped.has(o.type_id)) {
      return { ref: o.alt, markup: o.price / o.alt - 1, tag: "JITA" };
    }
    return { ref: o.jita, markup: o.markup, tag: o.gal ? "AVG" : null };
  }

  function parseAmt(id, fallback) {
    const raw = ($(id).value || "").trim().toLowerCase().replace(/,/g, "");
    const m = raw.match(/^([\d.]+)\s*([kmb])?$/);
    if (!m) return fallback;
    const mult = { k: 1e3, m: 1e6, b: 1e9 }[m[2]] || 1;
    const v = parseFloat(m[1]) * mult;
    return Number.isFinite(v) && v >= 0 ? v : fallback;
  }
  const minValue = () => parseAmt("min-value", 1_000_000);
  let doctrineTypes = new Set();
  const sort = { key: "markup", dir: -1 };

  function passesFilters(o) {
    const q = $("search").value.trim().toLowerCase();
    if (q && !(o.name || "").toLowerCase().includes(q)) return false;
    if (filters.min) {
      const basis = filters.minMode === "unit" ? o.price : o.price * o.volume;
      const x = minValue();
      if (filters.minDir === "<" ? basis < x : basis > x) return false;
    }
    if (filters.qty) {
      const x = parseAmt("qty-value", 10);
      if (filters.qtyDir === "<" ? o.volume < x : o.volume > x) return false;
    }
    if (filters.cat === "all") return true;
    if (filters.cat === "doctrine") return doctrineTypes.has(o.type_id);
    if (filters.cat === "caps") return !!o.capital;
    if (o.cat == null) return filters.cat === "nonfit";
    if (filters.cat === "nonfit") return !CATS.fit.has(o.cat);
    return CATS[filters.cat].has(o.cat);
  }

  // --- EVE-style clock (UTC) ---
  function tickClock() {
    const now = new Date();
    $("clock").textContent = now.toISOString().slice(11, 19) + " EVE";
  }
  setInterval(tickClock, 1000);
  tickClock();

  function fmtIsk(n) {
    if (n == null) return "—";
    return n.toLocaleString("en-US", { maximumFractionDigits: n < 100 ? 2 : 0 }) + " ISK";
  }

  function fmtAge(iso) {
    if (!iso) return "never";
    const mins = Math.round((Date.now() - new Date(iso).getTime()) / 60000);
    if (mins < 1) return "just now";
    if (mins < 60) return `${mins} min ago`;
    const h = Math.floor(mins / 60);
    return `${h}h ${mins % 60}m ago`;
  }

  function verdictFor(markup, threshold) {
    const pct = Math.round(markup * 100);
    if (pct <= -15) return SAINT;
    if (pct <= -7) return SUPPORTER;
    if (pct <= 0) return LOCAL;
    for (const cand of VERDICTS) {
      if (pct >= Math.round((cand.min ?? threshold) * 100)) return cand;
    }
    if (pct >= 19) return SUS;
    return HONEST;
  }

  function syncButtons() {
    for (const b of document.querySelectorAll(".cbtn")) {
      b.classList.toggle("on", b.dataset.cat === filters.cat);
    }
    $("caps-notice").classList.toggle("hidden", filters.cat !== "caps");
    for (const b of document.querySelectorAll(".vbtn")) {
      b.classList.toggle("on", vFilter.size === 0 || (b.dataset.v !== "all" && vFilter.has(Number(b.dataset.v))));
    }
  }

  function wake() {
    touched = true;
    syncButtons();
    render();
  }

  function render() {
    if (!touched) {
      if (!data) return;
      $("summary").innerHTML = "";
      $("results-body").innerHTML =
        '<tr><td colspan="6" class="placeholder">▸ PICK A FILTER, A VERDICT, OR SEARCH AN ITEM TO SCAN THE MARKET ◂</td></tr>';
      $("scan-info").innerHTML =
        `LAST SCAN: <b>${fmtAge(data.generated)}</b> · SYSTEM: <b>${escapeHtml(data.system || "XHQ-7V")}</b> · ${(data.orders || []).length} sell orders on file`;
      $("results").classList.remove("hidden");
      return;
    }
    if (!data) return;
    const threshold = Math.max(0, Number($("threshold").value) || 30) / 100;
    const showAll = $("show-all").checked;
    const tl = $("threshold-label");
    if (tl) tl.textContent = Math.round(threshold * 100);

    const structNames = data.structures || {};
    const rows = [];
    let offenders = 0;
    let judged = 0;

    const sortCmp = (a, b) => {
      if (sort.key === "name") {
        return sort.dir * (a.name || "").localeCompare(b.name || "");
      }
      let va, vb;
      if (sort.key === "markup") { va = effOf(a).markup; vb = effOf(b).markup; }
      else if (sort.key === "jita") { va = effOf(a).ref; vb = effOf(b).ref; }
      else { va = a[sort.key]; vb = b[sort.key]; }
      return sort.dir * ((va ?? -Infinity) - (vb ?? -Infinity));
    };
    const orders = (data.orders || []).slice();
    orders.sort(sortCmp);
    for (const th of document.querySelectorAll("th.sortable")) {
      th.querySelector(".arrow").textContent =
        th.dataset.key === sort.key ? (sort.dir === 1 ? " ▲" : " ▼") : " ·";
    }

    let noJita = 0;
    let candidates = [];
    for (const o of orders) {
      if (o.jita == null || o.markup == null) { noJita++; continue; } // nothing to judge against
      if (!passesFilters(o)) continue;
      candidates.push(o);
    }
    if (orderMode !== "all") {
      const byType = new Map();
      for (const o of candidates) {
        const best = byType.get(o.type_id);
        if (!best || (orderMode === "cheapest" ? o.price < best.price : o.price > best.price)) {
          byType.set(o.type_id, o);
        }
      }
      candidates = [...byType.values()].sort(sortCmp);
    }
    for (const o of candidates) {
      judged++;
      const eff = effOf(o);
      const isOffender = Math.round(eff.markup * 100) >= Math.round(threshold * 100);
      if (isOffender) offenders++;
      if (!isOffender && !showAll) continue;

      const v = verdictFor(eff.markup, threshold);
      if (vFilter.size && !vFilter.has(v.tier)) continue;
      const tr = document.createElement("tr");
      tr.className = "tier" + v.tier;
      const structName = structNames[o.location_id] || "structure " + o.location_id;
      const tagHtml = eff.tag
        ? ` <span class="galtag${o.alt != null ? " galclick" : ""}"${o.alt != null ? ` data-tid="${o.type_id}"` : ""} title="${eff.tag === "AVG"
            ? "Judged against the galaxy-wide average price" + (o.alt != null ? " — click to compare vs Jita" : " (nothing sold in Jita)")
            : "Compared against Jita — click to go back to the galaxy average"}">${eff.tag}</span>`
        : "";
      tr.innerHTML = `
        <td class="left ${v.cls}"><span class="verdict">${v.label}</span></td>
        <td class="left">
          <a class="itemname" href="https://evetycoon.com/market/${o.type_id}" target="_blank" rel="noopener">${escapeHtml(o.name || "type " + o.type_id)}</a>
          <span class="struct">${escapeHtml(structName)}</span>
        </td>
        <td class="num">${o.volume.toLocaleString("en-US")}</td>
        <td class="num">${fmtIsk(o.price)}</td>
        <td class="num">${fmtIsk(eff.ref)}${tagHtml}</td>
        <td class="num markup">${eff.markup >= 0 ? "+" : ""}${Math.round(eff.markup * 100)}%</td>`;
      rows.push(tr);
    }

    const body = $("results-body");
    body.replaceChildren(...rows);

    const summary = $("summary");
    if (offenders === 0) {
      summary.innerHTML = `<span class="ok">NOBODY IS BEING AN ASSHOLE.</span> <span class="dim">(${judged} orders judged — a miracle in New Eden)</span>`;
    } else {
      const refLabel = filters.cat === "caps" ? "JITA / GALACTIC AVG" : "JITA";
      summary.innerHTML = `<span class="count">${offenders}</span> OF ${judged} SELL ORDERS ARE (&ge;${Math.round(threshold * 100)}%) OVER ${refLabel}`;
    }

    $("scan-info").innerHTML =
      `LAST SCAN: <b>${fmtAge(data.generated)}</b> · SYSTEM: <b>${escapeHtml(data.system || "XHQ-7V")}</b>` +
      (noJita > 0 ? ` · <span class="dim">${noJita} orders skipped (no Jita price)</span>` : "");

    $("results").classList.remove("hidden");
  }

  function escapeHtml(s) {
    return String(s).replace(/[&<>"']/g, (c) => ({
      "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;",
    }[c]));
  }

  function log(msg, isErr) {
    $("status").innerHTML = isErr ? `<span class="err">${escapeHtml(msg)}</span>` : escapeHtml(msg);
  }

  async function load() {
    fetch("doctrine-items.json", { cache: "no-cache" })
      .then((r) => (r.ok ? r.json() : null))
      .then((d) => { if (d?.types) { doctrineTypes = new Set(d.types); render(); } })
      .catch(() => {});
    const mock = new URLSearchParams(location.search).has("mock");
    if (mock) {
      data = mockData();
      log("");
      render();
      return;
    }
    try {
      const res = await fetch("data.json", { cache: "no-cache" });
      if (!res.ok) throw new Error("HTTP " + res.status);
      data = await res.json();
      if (!data.generated) {
        log("NO SCAN DATA YET. Run the 'update market data' workflow in GitHub Actions to generate data.json.", true);
        $("scan-info").textContent = "AWAITING FIRST SCAN";
        return;
      }
      log("");
      render();
    } catch (e) {
      log("UPLINK FAILURE: could not load data.json (" + e.message + ")", true);
      $("scan-info").textContent = "UPLINK OFFLINE";
    }
  }

  // Mock data for local visual testing: open index.html?mock=1
  function mockData() {
    return {
      generated: new Date(Date.now() - 17 * 60000).toISOString(),
      system: "XHQ-7V",
      structures: { "1035949018593": "XHQ-7V - Immortalis Fortizar" },
      orders: [
        { type_id: 12005, name: "Ishtar", price: 412000000, jita: 318000000, volume: 3, location_id: "1035949018593", markup: 0.2956, cat: 6 },
        { type_id: 19722, name: "Naglfar", price: 5900000000, jita: 3480000000, volume: 2, location_id: "1035949018593", markup: 0.6954, cat: 6, capital: 1, gal: 1, alt: 4200000000 },
        { type_id: 41443, name: "Capital Ancillary Shield Booster", price: 99000000, jita: 62000000, volume: 4, location_id: "1035949018593", markup: 0.5968, cat: 7, capital: 1 },
        { type_id: 2048,  name: "Damage Control II", price: 2100000, jita: 690000, volume: 14, location_id: "1035949018593", markup: 2.0435, cat: 7 },
        { type_id: 12058, name: "Nanite Repair Paste", price: 38000, jita: 30500, volume: 5000, location_id: "1035949018593", markup: 0.2459, cat: 8 },
        { type_id: 3841,  name: "Large Shield Extender II", price: 1310000, jita: 1240000, volume: 22, location_id: "1035949018593", markup: 0.0565, cat: 7 },
        { type_id: 16273, name: "Liquid Ozone", price: 890, jita: 410, volume: 250000, location_id: "1035949018593", markup: 1.1707, cat: 4 },
        { type_id: 24700, name: "Myrmidon", price: 92000000, jita: 58000000, volume: 1, location_id: "1035949018593", markup: 0.5862, cat: 6 },
        { type_id: 31716, name: "Medium Core Defense Field Extender I", price: 3400000, jita: 2900000, volume: 8, location_id: "1035949018593", markup: 0.1724, cat: 7 },
        { type_id: 27361, name: "Caldari Navy Antimatter Charge M", price: 480, jita: 455, volume: 120000, location_id: "1035949018593", markup: 0.0549, cat: 8 },
        { type_id: 12608, name: "Hobgoblin II", price: 690000, jita: 310000, volume: 45, location_id: "1035949018593", markup: 1.2258, cat: 18 },
        { type_id: 526, name: "Stasis Webifier I", price: 850000, jita: 1000000, volume: 12, location_id: "1035949018593", markup: -0.15, cat: 7 },
        { type_id: 527, name: "X5 Enduring Stasis Webifier", price: 1800000, jita: 2000000, volume: 6, location_id: "1035949018593", markup: -0.10, cat: 7 },
        { type_id: 2456, name: "Fleeting Compact Stasis Webifier", price: 1940000, jita: 2000000, volume: 3, location_id: "1035949018593", markup: -0.03, cat: 7 },
      ],
    };
  }

  $("f-min").addEventListener("click", () => {
    filters.min = !filters.min;
    $("f-min").classList.toggle("on", filters.min);
    render();
  });
  for (const btn of document.querySelectorAll(".vbtn")) {
    btn.addEventListener("click", () => {
      if (btn.dataset.v === "all") vFilter.clear();
      else {
        const t = Number(btn.dataset.v);
        vFilter.has(t) ? vFilter.delete(t) : vFilter.add(t);
      }
      for (const b of document.querySelectorAll(".vbtn")) {
        b.classList.toggle("on", vFilter.size === 0 || (b.dataset.v !== "all" && vFilter.has(Number(b.dataset.v))));
      }
      wake();
    });
  }

  for (const btn of document.querySelectorAll(".cbtn")) {
    btn.addEventListener("click", () => {
      filters.cat = btn.dataset.cat;
      for (const b of document.querySelectorAll(".cbtn")) b.classList.toggle("on", b === btn);
      wake();
    });
  }

  for (const th of document.querySelectorAll("th.sortable")) {
    th.addEventListener("click", () => {
      if (sort.key === th.dataset.key) sort.dir = -sort.dir;
      else { sort.key = th.dataset.key; sort.dir = th.dataset.key === "name" ? 1 : -1; }
      wake();
    });
  }

  $("min-dir").addEventListener("click", () => {
    filters.minDir = filters.minDir === "<" ? ">" : "<";
    $("min-dir").innerHTML = filters.minDir === "<" ? "&lt;" : "&gt;";
    wake();
  });
  $("min-mode").addEventListener("click", () => {
    filters.minMode = filters.minMode === "unit" ? "order" : "unit";
    $("min-mode").textContent = filters.minMode === "unit" ? "UNIT" : "ORDER";
    wake();
  });
  $("f-qty").addEventListener("click", () => {
    filters.qty = !filters.qty;
    $("f-qty").classList.toggle("on", filters.qty);
    wake();
  });
  $("qty-dir").addEventListener("click", () => {
    filters.qtyDir = filters.qtyDir === "<" ? ">" : "<";
    $("qty-dir").innerHTML = filters.qtyDir === "<" ? "&lt;" : "&gt;";
    wake();
  });
  $("qty-value").addEventListener("input", wake);
  $("results-body").addEventListener("click", (e) => {
    const tag = e.target.closest(".galclick");
    if (!tag) return;
    const tid = Number(tag.dataset.tid);
    flipped.has(tid) ? flipped.delete(tid) : flipped.add(tid);
    render();
  });
  $("search").addEventListener("input", wake);
  for (const b of document.querySelectorAll(".obtn")) {
    b.addEventListener("click", () => {
      orderMode = b.dataset.mode;
      for (const x of document.querySelectorAll(".obtn")) x.classList.toggle("on", x === b);
      wake();
    });
  }
  $("min-value").addEventListener("input", wake);
  $("threshold").addEventListener("input", wake);
  $("show-all").addEventListener("change", wake);
  load();
})();
