/* WHO IS BEING AN ASSHOLE? — contracts page
 * Reads contracts.json (generated by the GitHub Actions cron job).
 * Unlike market orders, contract issuers are public — so this page names names.
 */
(() => {
  "use strict";

  const $ = (id) => document.getElementById(id);

  const VERDICTS = [
    { min: -Infinity, label: "░ HONEST", cls: "v0", tier: 0 },
    { min: 0.20,      label: "▒ CHEEKY", cls: "v1", tier: 1 },
    { min: 0.50,      label: "▓ ASSHOLE", cls: "v2", tier: 2 },
    { min: 1.00,      label: "█ GALACTIC ASSHOLE", cls: "v3", tier: 3 },
  ];

  let data = null;
  let scalpLog = null; // {entries: {id: {...}}}
  const filters = { cat: "all" };
  const sort = { key: "markup", dir: -1 };
  const SCALP_TRACKING_SINCE = "2026-09-04";
  const NOTICE_UNTIL = new Date("2026-12-04");

  function tickClock() {
    $("clock").textContent = new Date().toISOString().slice(11, 19) + " EVE";
  }
  setInterval(tickClock, 1000);
  tickClock();

  function fmtIsk(n) {
    if (n == null) return "—";
    if (n >= 1e9) return (n / 1e9).toFixed(2) + "B ISK";
    if (n >= 1e6) return (n / 1e6).toFixed(1) + "M ISK";
    return Math.round(n).toLocaleString("en-US") + " ISK";
  }

  function fmtAge(iso) {
    if (!iso) return "never";
    const mins = Math.round((Date.now() - new Date(iso).getTime()) / 60000);
    if (mins < 1) return "just now";
    if (mins < 60) return `${mins} min ago`;
    return `${Math.floor(mins / 60)}h ${mins % 60}m ago`;
  }

  function verdictFor(markup, threshold) {
    let v = VERDICTS[0];
    for (const cand of VERDICTS) {
      const min = cand.tier === 1 ? threshold : cand.min;
      if (markup >= min) v = cand;
    }
    return v;
  }

  function escapeHtml(s) {
    return String(s).replace(/[&<>"']/g, (c) => ({
      "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;",
    }[c]));
  }

  function render() {
    if (!data) return;
    const threshold = Math.max(0, Number($("threshold").value) || 30) / 100;
    const showAll = $("show-all").checked;
    $("threshold-label").textContent = Math.round(threshold * 100);

    const scalpView = filters.cat === "scalp" || filters.cat === "scalplog";
    $("scalp-notice").classList.toggle("hidden", !(scalpView && new Date() < NOTICE_UNTIL));
    document.querySelector('.cbtn[data-cat="scalplog"]').hidden = !scalpView;

    if (filters.cat === "scalplog") { renderLog(threshold); return; }

    const list = (data.contracts || []).slice();
    list.sort((a, b) => {
      let va = a[sort.key], vb = b[sort.key];
      if (sort.key === "title" || sort.key === "issuer") {
        return sort.dir * String(va || "").localeCompare(String(vb || ""));
      }
      return sort.dir * ((va ?? -Infinity) - (vb ?? -Infinity));
    });
    for (const th of document.querySelectorAll("th.sortable")) {
      th.querySelector(".arrow").textContent =
        th.dataset.key === sort.key ? (sort.dir === 1 ? " ▲" : " ▼") : " ·";
    }

    const rows = [];
    let offenders = 0, judged = 0, unjudged = 0;
    for (const c of list) {
      if (filters.cat === "doctrine" && !c.doctrine) continue;
      if (filters.cat === "scalp" && !c.scalp) continue;
      if (c.markup == null) { unjudged++; continue; }
      judged++;
      const isOffender = c.markup >= threshold || !!c.scalp;
      if (isOffender) offenders++;
      if (!isOffender && !showAll) continue;

      const v = verdictFor(c.markup, threshold);
      const tr = document.createElement("tr");
      tr.className = "tier" + v.tier;
      const label = c.title || c.hull || `contract ${c.id}`;
      let sub = [c.hull && c.hull !== c.title ? c.hull : null, `${c.items} items`]
        .filter(Boolean).join(" · ");
      if (c.scalp) {
        const gain = Math.round((c.price / c.scalp.paid - 1) * 100);
        sub = `SCALPED — bought from ${c.scalp.from} for ${fmtIsk(c.scalp.paid)}, relisted +${gain}% · ` + sub;
      }
      tr.innerHTML = `
        <td class="left ${v.cls}"><span class="verdict">${v.label}</span></td>
        <td class="left">
          <span class="itemname">${escapeHtml(label)}</span>${c.doctrine ? ' <span class="galtag" title="Contains a CVA doctrine ship">DOCTRINE</span>' : ""}${c.scalp ? ' <span class="scalptag" title="Same physical item bought cheaper and relisted">SCALP</span>' : ""}
          <span class="struct${c.scalp ? " scalpline" : ""}">${escapeHtml(sub)}</span>
        </td>
        <td class="left"><a class="itemname" href="https://zkillboard.com/search/${encodeURIComponent(c.issuer)}/" target="_blank" rel="noopener">${escapeHtml(c.issuer)}</a></td>
        <td class="num">${fmtIsk(c.price)}</td>
        <td class="num">${fmtIsk(c.value)}${c.est ? ' <span class="galtag" title="Some contents (e.g. BPCs) could not be priced — true value is higher">±</span>' : ""}</td>
        <td class="num markup">${c.markup >= 0 ? "+" : ""}${Math.round(c.markup * 100)}%</td>`;
      rows.push(tr);
    }
    $("results-body").replaceChildren(...rows);

    const scope = filters.cat === "doctrine" ? "DOCTRINE-SHIP CONTRACTS" : "CONTRACTS";
    const summary = $("summary");
    if (offenders === 0) {
      summary.innerHTML = `<span class="ok">NOBODY IS BEING AN ASSHOLE.</span> <span class="dim">(${judged} ${scope.toLowerCase()} judged)</span>`;
    } else {
      summary.innerHTML = `<span class="count">${offenders}</span> OF ${judged} ${scope} ARE BEING ASSHOLES` +
        ` <span class="dim">(&ge;${Math.round(threshold * 100)}% over contents value)</span>`;
    }
    $("scan-info").innerHTML =
      `LAST SCAN: <b>${fmtAge(data.generated)}</b> · SYSTEM: <b>${escapeHtml(data.system || "XHQ-7V")}</b>` +
      (unjudged > 0 ? ` · <span class="dim">${unjudged} skipped (item swaps / unpriceable)</span>` : "");
    $("results").classList.remove("hidden");
  }

  // The permanent hall of shame: every scalp ever caught, live or not.
  function renderLog(threshold) {
    const entries = Object.values(scalpLog?.entries || {});
    entries.sort((a, b) => {
      let va = a[sort.key], vb = b[sort.key];
      if (sort.key === "title" || sort.key === "issuer") {
        return sort.dir * String(va || "").localeCompare(String(vb || ""));
      }
      return sort.dir * ((va ?? -Infinity) - (vb ?? -Infinity));
    });

    const rows = [];
    let live = 0;
    for (const e of entries) {
      if (!e.gone) live++;
      const v = verdictFor(e.markup ?? 0, threshold);
      const gain = Math.round((e.price / e.scalp.paid - 1) * 100);
      const status = !e.gone
        ? "STILL LISTED"
        : new Date(e.gone) < new Date(e.expires)
          ? `SOLD ~${String(e.gone).slice(0, 10)}`
          : `EXPIRED ${String(e.gone).slice(0, 10)}`;
      const sub = `SCALPED — bought from ${e.scalp.from} for ${fmtIsk(e.scalp.paid)}, relisted +${gain}% · ` +
        `caught ${String(e.detected).slice(0, 10)} · ${status}` + (e.hull && e.hull !== e.title ? ` · ${e.hull}` : "");
      const tr = document.createElement("tr");
      tr.className = "tier" + v.tier + (e.gone ? " gonerow" : "");
      tr.innerHTML = `
        <td class="left ${v.cls}"><span class="verdict">${v.label}</span></td>
        <td class="left">
          <span class="itemname">${escapeHtml(e.title || e.hull || `contract ${e.id}`)}</span>${e.doctrine ? ' <span class="galtag">DOCTRINE</span>' : ""} <span class="scalptag">SCALP</span>
          <span class="struct scalpline">${escapeHtml(sub)}</span>
        </td>
        <td class="left"><a class="itemname" href="https://zkillboard.com/search/${encodeURIComponent(e.issuer)}/" target="_blank" rel="noopener">${escapeHtml(e.issuer)}</a></td>
        <td class="num">${fmtIsk(e.price)}</td>
        <td class="num">${fmtIsk(e.value)}</td>
        <td class="num markup">${e.markup != null ? (e.markup >= 0 ? "+" : "") + Math.round(e.markup * 100) + "%" : "—"}</td>`;
      rows.push(tr);
    }
    $("results-body").replaceChildren(...rows);
    const summary = $("summary");
    if (entries.length === 0) {
      summary.innerHTML = `<span class="ok">NO SCALPS ON RECORD YET.</span> <span class="dim">(tracking since ${SCALP_TRACKING_SINCE})</span>`;
    } else {
      summary.innerHTML = `<span class="count">${entries.length}</span> SCALP${entries.length === 1 ? "" : "S"} ON RECORD SINCE ${SCALP_TRACKING_SINCE}` +
        ` <span class="dim">(${live} still listed)</span>`;
    }
    $("scan-info").innerHTML = `LAST SCAN: <b>${fmtAge(data.generated)}</b> · SYSTEM: <b>${escapeHtml(data.system || "XHQ-7V")}</b> · PERMANENT RECORD`;
    $("results").classList.remove("hidden");
  }

  function log(msg, isErr) {
    $("status").innerHTML = isErr ? `<span class="err">${escapeHtml(msg)}</span>` : escapeHtml(msg);
  }

  async function load() {
    fetch("scalp-log.json", { cache: "no-cache" })
      .then((r) => (r.ok ? r.json() : null))
      .then((d) => { if (d) { scalpLog = d; if (filters.cat === "scalplog") render(); } })
      .catch(() => {});
    try {
      const res = await fetch("contracts.json", { cache: "no-cache" });
      if (!res.ok) throw new Error("HTTP " + res.status);
      data = await res.json();
      if (!data.generated) {
        log("NO CONTRACT DATA YET. Run the 'update market data' workflow in GitHub Actions.", true);
        $("scan-info").textContent = "AWAITING FIRST SCAN";
        return;
      }
      log("");
      render();
    } catch (e) {
      log("UPLINK FAILURE: could not load contracts.json (" + e.message + ")", true);
      $("scan-info").textContent = "UPLINK OFFLINE";
    }
  }

  for (const btn of document.querySelectorAll(".cbtn")) {
    btn.addEventListener("click", () => {
      filters.cat = btn.dataset.cat;
      for (const b of document.querySelectorAll(".cbtn")) b.classList.toggle("on", b === btn);
      render();
    });
  }
  for (const th of document.querySelectorAll("th.sortable")) {
    th.addEventListener("click", () => {
      if (sort.key === th.dataset.key) sort.dir = -sort.dir;
      else { sort.key = th.dataset.key; sort.dir = ["title", "issuer"].includes(th.dataset.key) ? 1 : -1; }
      render();
    });
  }
  $("threshold").addEventListener("input", render);
  $("show-all").addEventListener("change", render);
  load();
})();
