/* WHO IS BEING AN ASSHOLE? — contracts page
 * Reads contracts.json (generated by the GitHub Actions cron job).
 * Unlike market orders, contract issuers are public — so this page names names.
 */
(() => {
  "use strict";

  const $ = (id) => document.getElementById(id);

  const VERDICTS = [
    { min: -Infinity, label: "░ HONEST", cls: "v0", tier: 0 },
    { min: 0.20,      label: "▒ CHEEKY", cls: "v1", tier: 1 },
    { min: 0.50,      label: "▓ ASSHOLE", cls: "v2", tier: 2 },
    { min: 1.00,      label: "█ GALACTIC ASSHOLE", cls: "v3", tier: 3 },
  ];

  let data = null;
  const filters = { cat: "all" };
  const sort = { key: "markup", dir: -1 };

  function tickClock() {
    $("clock").textContent = new Date().toISOString().slice(11, 19) + " EVE";
  }
  setInterval(tickClock, 1000);
  tickClock();

  function fmtIsk(n) {
    if (n == null) return "—";
    if (n >= 1e9) return (n / 1e9).toFixed(2) + "B ISK";
    if (n >= 1e6) return (n / 1e6).toFixed(1) + "M ISK";
    return Math.round(n).toLocaleString("en-US") + " ISK";
  }

  function fmtAge(iso) {
    if (!iso) return "never";
    const mins = Math.round((Date.now() - new Date(iso).getTime()) / 60000);
    if (mins < 1) return "just now";
    if (mins < 60) return `${mins} min ago`;
    return `${Math.floor(mins / 60)}h ${mins % 60}m ago`;
  }

  function verdictFor(markup, threshold) {
    let v = VERDICTS[0];
    for (const cand of VERDICTS) {
      const min = cand.tier === 1 ? threshold : cand.min;
      if (markup >= min) v = cand;
    }
    return v;
  }

  function escapeHtml(s) {
    return String(s).replace(/[&<>"']/g, (c) => ({
      "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;",
    }[c]));
  }

  function render() {
    if (!data) return;
    const threshold = Math.max(0, Number($("threshold").value) || 20) / 100;
    const showAll = $("show-all").checked;
    $("threshold-label").textContent = Math.round(threshold * 100);

    const list = (data.contracts || []).slice();
    list.sort((a, b) => {
      let va = a[sort.key], vb = b[sort.key];
      if (sort.key === "title" || sort.key === "issuer") {
        return sort.dir * String(va || "").localeCompare(String(vb || ""));
      }
      return sort.dir * ((va ?? -Infinity) - (vb ?? -Infinity));
    });
    for (const th of document.querySelectorAll("th.sortable")) {
      th.querySelector(".arrow").textContent =
        th.dataset.key === sort.key ? (sort.dir === 1 ? " ▲" : " ▼") : " ·";
    }

    const rows = [];
    let offenders = 0, judged = 0, unjudged = 0;
    for (const c of list) {
      if (filters.cat === "doctrine" && !c.doctrine) continue;
      if (c.markup == null) { unjudged++; continue; }
      judged++;
      const isOffender = c.markup >= threshold;
      if (isOffender) offenders++;
      if (!isOffender && !showAll) continue;

      const v = verdictFor(c.markup, threshold);
      const tr = document.createElement("tr");
      tr.className = "tier" + v.tier;
      const label = c.title || c.hull || `contract ${c.id}`;
      const sub = [c.hull && c.hull !== c.title ? c.hull : null, `${c.items} items`]
        .filter(Boolean).join(" · ");
      tr.innerHTML = `
        <td class="left ${v.cls}"><span class="verdict">${v.label}</span></td>
        <td class="left">
          <span class="itemname">${escapeHtml(label)}</span>${c.doctrine ? ' <span class="galtag" title="Contains a CVA doctrine ship">DOCTRINE</span>' : ""}
          <span class="struct">${escapeHtml(sub)}</span>
        </td>
        <td class="left"><a class="itemname" href="https://zkillboard.com/search/${encodeURIComponent(c.issuer)}/" target="_blank" rel="noopener">${escapeHtml(c.issuer)}</a></td>
        <td class="num">${fmtIsk(c.price)}</td>
        <td class="num">${fmtIsk(c.value)}${c.est ? ' <span class="galtag" title="Some contents (e.g. BPCs) could not be priced — true value is higher">±</span>' : ""}</td>
        <td class="num markup">${c.markup >= 0 ? "+" : ""}${Math.round(c.markup * 100)}%</td>`;
      rows.push(tr);
    }
    $("results-body").replaceChildren(...rows);

    const scope = filters.cat === "doctrine" ? "DOCTRINE-SHIP CONTRACTS" : "CONTRACTS";
    const summary = $("summary");
    if (offenders === 0) {
      summary.innerHTML = `<span class="ok">NOBODY IS BEING AN ASSHOLE.</span> <span class="dim">(${judged} ${scope.toLowerCase()} judged)</span>`;
    } else {
      summary.innerHTML = `<span class="count">${offenders}</span> OF ${judged} ${scope} ARE BEING ASSHOLES` +
        ` <span class="dim">(&ge;${Math.round(threshold * 100)}% over contents value)</span>`;
    }
    $("scan-info").innerHTML =
      `LAST SCAN: <b>${fmtAge(data.generated)}</b> · SYSTEM: <b>${escapeHtml(data.system || "XHQ-7V")}</b>` +
      (unjudged > 0 ? ` · <span class="dim">${unjudged} skipped (item swaps / unpriceable)</span>` : "");
    $("results").classList.remove("hidden");
  }

  function log(msg, isErr) {
    $("status").innerHTML = isErr ? `<span class="err">${escapeHtml(msg)}</span>` : escapeHtml(msg);
  }

  async function load() {
    try {
      const res = await fetch("contracts.json", { cache: "no-cache" });
      if (!res.ok) throw new Error("HTTP " + res.status);
      data = await res.json();
      if (!data.generated) {
        log("NO CONTRACT DATA YET. Run the 'update market data' workflow in GitHub Actions.", true);
        $("scan-info").textContent = "AWAITING FIRST SCAN";
        return;
      }
      log("");
      render();
    } catch (e) {
      log("UPLINK FAILURE: could not load contracts.json (" + e.message + ")", true);
      $("scan-info").textContent = "UPLINK OFFLINE";
    }
  }

  for (const btn of document.querySelectorAll(".cbtn")) {
    btn.addEventListener("click", () => {
      filters.cat = btn.dataset.cat;
      for (const b of document.querySelectorAll(".cbtn")) b.classList.toggle("on", b === btn);
      render();
    });
  }
  for (const th of document.querySelectorAll("th.sortable")) {
    th.addEventListener("click", () => {
      if (sort.key === th.dataset.key) sort.dir = -sort.dir;
      else { sort.key = th.dataset.key; sort.dir = ["title", "issuer"].includes(th.dataset.key) ? 1 : -1; }
      render();
    });
  }
  $("threshold").addEventListener("input", render);
  $("show-all").addEventListener("change", render);
  load();
})();
